server:
  port: 9380
  context-path: /applicazioni
  
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.cloud: DEBUG
    guru.springframework.controllers: DEBUG
    org.hibernate: DEBUG


zuul:
  routes:
    api-applicazione-ricerca:
      path: /api/anagrafiche/**
      url: http://localhost:9480/applicazioni/api/anagrafiche
    applicazione-ricerca:
      path: /anagrafiche/**
      url: http://localhost:9480/applicazioni/
    api-applicazione-sale-riunioni:
      path: /api/sale/**
      url: http://localhost:9481/applicazioni/api/sale
    applicazione-sale-riunioni:
      path: /sale/**
      url: http://localhost:9481/applicazioni/